### ISSUE TITLE
[v 2.11.2] Cannot pick the King Rat's Cheese

### ISSUE THREAD

**Issue by fcaneva-arg** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#11]
There is a crash whenever you want to pick the King Rat's Cheese. I ran the game through Windows CMD to get the stack trace, and this is what I get:

```
[Controllers] added manager for application, 1 managers active
[GAME] @@ You return to floor 5 of the dungeon.
[GAME] @@ Badge unlocked: !!!NO TEXT FOUND!!! (!!!NO TEXT FOUND!!!).
[GAME] You picked up: Cheese.
[GAME] java.lang.NullPointerException: Cannot invoke "com.watabou.utils.RectF.width()" because "frame" is null
        at com.watabou.noosa.Image.frame(Image.java:80)
        at com.shatteredpixel.shatteredpixeldungeon.effects.BadgeBanner.setup(BadgeBanner.java:76)
        at com.shatteredpixel.shatteredpixeldungeon.effects.BadgeBanner.<init>(BadgeBanner.java:70)
        at com.shatteredpixel.shatteredpixeldungeon.effects.BadgeBanner.show(BadgeBanner.java:204)
        at com.shatteredpixel.shatteredpixeldungeon.scenes.PixelScene$1.call(PixelScene.java:306)
        at com.watabou.noosa.Game$1.run(Game.java:313)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:208)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
        at com.shatteredpixel.shatteredpixeldungeon.desktop.DesktopLauncher.main(DesktopLauncher.java:190)
```
I think this might be because the game cannot load the "Cheese" badge.
Also, I get a GUI error message `INVALID MESSAGE WITH QUOTES`, presumably that it could not found the right string for obtaining the Cheese.

### Steps to reproduce
- Start a game
- Get to level 5, and search for the King Rat's hideout. You may want to kill the Goo to have all the level available to chase the Rat.
- Start trading; after the 50th trading, you'll get the Cheese.
- Pick it up; the game crashes instantly.

**Comment by NyanMC** [comment]
this also occurs in v2.11.3
