### ISSUE TITLE
[ExpPD-2.11.3]Crash when going down a floor

### ISSUE THREAD

**Issue by Redxjak** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#12]
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: samsung
Device: p3q
Model: SM-G998U
Manufacturer: samsung
Product: p3qsqw
SDK: 31
Release: 12

***** APP INFO 
Version: ExpPD-2.11.3
Installed On: 2022-09-15 19:02:28
Updated On: 2022-10-16 22:06:39
Current Date: 2022-10-16 22:07:15

***** ERROR LOG 
java.lang.RuntimeException: fatal error occured while moving between floors. Seed:263788643691 depth:16
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene.update(InterlevelScene.java:19)
	at c.b.a.o.a.m.onDrawFrame(AndroidGraphics.java:73)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at com.shatteredpixel.shatteredpixeldungeon.levels.painters.RegularPainter.paint(RegularPainter.java:165)
	at com.shatteredpixel.shatteredpixeldungeon.levels.RegularLevel.build(RegularLevel.java:8)
	at com.shatteredpixel.shatteredpixeldungeon.levels.Level.create(Level.java:51)
	at com.shatteredpixel.shatteredpixeldungeon.Dungeon.newLevel(Dungeon.java:27)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene.access$300(InterlevelScene.java:167)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene$4.run(InterlevelScene.java:25)

***** END OF LOG *****

**Comment by Redxjak** [comment]
This happened in the last version as well.
