### ISSUE TITLE
Crash leaving dwarf king level?

### ISSUE THREAD

**Issue by Gabyalufix** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#22]
I think it's my fourth run, it crashes whenever I try going down from the dwarf king level. Crash report below.

***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Manufacturer: OnePlus
Product: OnePlus6T
SDK: 30
Release: 11

***** APP INFO 
Version: ExpPD-2.11.4
Installed On: 2023-03-19 23:15:39
Updated On: 2023-03-19 23:15:39
Current Date: 2023-03-26 11:04:56

***** ERROR LOG 
java.lang.RuntimeException: fatal error occured while moving between floors. Seed:3995201068322 depth:16
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene.update(InterlevelScene.java:19)
	at c.b.a.o.a.m.onDrawFrame(AndroidGraphics.java:73)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1591)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at com.shatteredpixel.shatteredpixeldungeon.levels.painters.RegularPainter.paint(RegularPainter.java:165)
	at com.shatteredpixel.shatteredpixeldungeon.levels.RegularLevel.build(RegularLevel.java:8)
	at com.shatteredpixel.shatteredpixeldungeon.levels.Level.create(Level.java:51)
	at com.shatteredpixel.shatteredpixeldungeon.Dungeon.newLevel(Dungeon.java:27)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene.access$300(InterlevelScene.java:167)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene$4.run(InterlevelScene.java:25)

***** END OF LOG *****

**Comment by Gabyalufix** [comment]
Resetting the level fixes the issue, so it's workable.

**Comment by MarsKamara** [comment]
I played on that device. what I usually do is try to skip the level entirely.
