### ISSUE TITLE
Crash when killing slime

### ISSUE THREAD

**Issue by DragonMaster14545** [TrashboxBobylev/Experienced-Pixel-Dungeon-Redone#65]
I get this crash when I kill a slime
![Screenshot_2024-05-28-15-56-11-902_com.trashboxbobylev.experiencedpixeldungeon.redone.jpg](https://github.com/TrashboxBobylev/Experienced-Pixel-Dungeon-Redone/assets/114180377/3ba9f323-7a8f-4b90-a32e-9ea7862a4114)

This is my inventory, in case it matters. I already drank one potion of luck

````
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: Redmi
Device: sweet
Model: M2101K6G
Manufacturer: Xiaomi
Product: sweet_eea
SDK: 30
Release: 11

***** APP INFO 
Version: ExpPD-2.18.0
Installed On: 2024-03-22 15:23:15
Updated On: 2024-05-26 16:34:18
Current Date: 2024-05-28 15:55:42

***** ERROR LOG 
java.lang.ArrayIndexOutOfBoundsException: length=6; index=-1
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Slime.createLoot(Unknown Source:18)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.rollToDropLoot(Unknown Source:28)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.die(Unknown Source:88)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Char.damage(Unknown Source:1252)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.damage(Unknown Source:33)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Slime.damage(Unknown Source:64)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Char.attack(SourceFile:2)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Char.attack(SourceFile:1)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.onAttackComplete(Unknown Source:2)
	at com.shatteredpixel.shatteredpixeldungeon.sprites.CharSprite.onComplete(SourceFile:1)
	at com.shatteredpixel.shatteredpixeldungeon.sprites.MobSprite.onComplete(Unknown Source:0)
	at com.watabou.noosa.MovieClip.updateAnimation(Unknown Source:68)
	at com.watabou.noosa.MovieClip.update(Unknown Source:7)
	at com.shatteredpixel.shatteredpixeldungeon.sprites.CharSprite.update(Unknown Source:28)
	at com.shatteredpixel.shatteredpixeldungeon.sprites.MobSprite.update(Unknown Source:28)
	at com.watabou.noosa.Group.update(Unknown Source:24)
	at com.watabou.noosa.Group.update(Unknown Source:24)
	at com.watabou.noosa.Scene.update(Unknown Source:0)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.PixelScene.update(Unknown Source:20)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene.update(Unknown Source:27)
	at com.watabou.noosa.Game.update(SourceFile:41)
	at com.watabou.noosa.Game.step(Unknown Source:22)
	at com.watabou.noosa.Game.render(SourceFile:71)
	at y.k.onDrawFrame(SourceFile:218)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)



***** END OF LOG *****

```

**Comment by DragonMaster14545** [comment]
I also tried dropping the exotic crystals, because they are the only thing that could alter the drops, that I could think of, but it still happens

**Comment by DragonMaster14545** [comment]
And for some reason, if my bat kills it, no crash

**Comment by DragonMaster14545** [comment]
Another correction, if my bat kills it AND I don't see it it doesn't crash, if I see it it crashes

**Comment by TrashboxBobylev** [comment]
Fixed in dev.
